# Generated by Django 4.1.2 on 2022-10-10 23:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('tour_name', models.CharField(max_length=300)),
                ('requestor_name', models.CharField(max_length=300)),
                ('requestor_email', models.EmailField(max_length=254)),
                ('alternate_contact', models.CharField(max_length=300)),
                ('attendees_akamai', models.IntegerField(default=0)),
                ('attendees_guests', models.IntegerField(default=0)),
                ('is_current_customer', models.BooleanField()),
                ('category', models.CharField(choices=[('existing customer', 'Existing Customer'), ('new prospect', 'New Prospect'), ('public relations / press / analysts', 'Public Relations / Press / Analysts'), ('investors', 'Investors'), ('akamai employees (internal tour)', 'Akamai Employees (Internal Tour)'), ('students / informal guests', 'Students / Informal Guests')], default='existing customer', max_length=50)),
                ('is_nocc_required', models.BooleanField()),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
