# Generated by Django 4.1.2 on 2022-11-07 00:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('Cambridge', 'Cambridge'), ('Krakow', 'Krakow'), ('Bangalore', 'Bangalore')], default='Cambridge', max_length=100)),
                ('avail_date_start', models.DateField()),
                ('avail_start_time', models.TimeField()),
                ('avail_end_time', models.TimeField()),
                ('time_slots', models.TimeField()),
                ('nocc_representatives_list', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('tour_name', models.CharField(max_length=300)),
                ('requestor_name', models.CharField(max_length=300)),
                ('requestor_email', models.EmailField(max_length=254)),
                ('poc_name', models.CharField(max_length=300)),
                ('poc_email', models.EmailField(max_length=254)),
                ('cc_this_request_to', models.EmailField(help_text='Ability to CC more people in order to receive feedback form + invitation to event once it has been approved.', max_length=254)),
                ('division', models.CharField(choices=[('P & RE', 'P & RE'), ('Customer & Industry', 'Customer & Industry'), ('marketing', 'Marketing'), ('Global Events', 'Global Events'), ('Marketing Strategy', 'Marketing Strategy'), ('Legal', 'Legal'), ('CTO', 'CTO'), ('CEO', 'CEO'), ('Global Sales', 'Global Sales'), ('Customer Success', 'Customer Success'), ('Global Services', 'Global Services'), ('Products & Enablement', 'Products & Enablement'), ('Compute', 'Compute'), ('Edge Delivery', 'Edge Delivery'), ('Edge Business Operations', 'Edge Business Operations'), ('Edge Experience', 'Edge Experience'), ('Other', 'Other')], default='P & RE', max_length=50)),
                ('location', models.CharField(choices=[('Cambridge', 'Cambridge'), ('Krakow', 'Krakow'), ('Bangalore', 'Bangalore')], default='Cambridge', max_length=100)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('nocc_personnel_required', models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='no', max_length=10)),
                ('category', models.CharField(choices=[('existing customer', 'Existing Customer'), ('new prospect', 'New Prospect'), ('public relations / press / analysts', 'Public Relations / Press / Analysts'), ('investors', 'Investors'), ('akamai employees (internal tour)', 'Akamai Employees (Internal Tour)'), ('students / informal guests', 'Students / Informal Guests')], default='existing customer', max_length=50)),
                ('attendees_akamai', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('attendees_guests', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('customer_or_group_name', models.CharField(max_length=200)),
                ('nocc_person_assigned', models.CharField(choices=[('None', 'None'), ('Adam', 'Adam'), ('Brian', 'Brian'), ('Charlie', 'Charlie')], default='None', max_length=30)),
                ('comment', models.TextField(blank=True, max_length=2000, null=True)),
                ('feedback', models.TextField(blank=True, default='No feedback yet', max_length=2000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('Requested', 'Requested'), ('Rejected', 'Rejected'), ('Approved', 'Approved')], default='Requested', max_length=20)),
            ],
        ),
    ]
