# Generated by Django 4.1.2 on 2022-10-11 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NoccSchedulerApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='is_current_customer',
            new_name='current_customer',
        ),
        migrations.RenameField(
            model_name='tour',
            old_name='is_nocc_required',
            new_name='nocc_required',
        ),
    ]
