# Generated by Django 4.1.2 on 2022-11-08 22:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NoccSchedulerApp', '0002_rename_avail_date_start_location_avail_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='time_interval',
            field=models.TimeField(default=datetime.time(1, 0)),
        ),
        migrations.AlterField(
            model_name='location',
            name='time_slots',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='tour',
            name='nocc_personnel_required',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=10),
        ),
    ]
