# Generated by Django 4.1.2 on 2022-11-09 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NoccSchedulerApp', '0004_remove_location_avail_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='opportunity_ID',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
