# Generated by Django 4.1.2 on 2022-11-09 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NoccSchedulerApp', '0005_tour_opportunity_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='type_of_customers',
            field=models.CharField(choices=[('Financial Services', 'Financial Services'), ('Media', 'Media'), ('High Tech', 'High Tech'), ('Retail + Commerce', 'Retail + Commerce'), ('Gaming/OTT', 'Gaming/OTT'), ('Healthcare/Life Science', 'Healthcare/Life Science'), ('Manufacturing', 'Manufacturing')], default='Media', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tour',
            name='category',
            field=models.CharField(choices=[('existing customer', 'Existing Customer'), ('new prospect', 'New Prospect'), ('public relations / press / analysts', 'Public Relations / Press / Analysts'), ('investors', 'Investors'), ('akamai employees (internal tour)', 'Akamai Employees (Internal Tour)'), ('students / informal guests', 'Students / Informal Guests')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tour',
            name='nocc_person_assigned',
            field=models.CharField(choices=[('None', 'None'), ('Adam', 'Adam'), ('Brian', 'Brian'), ('Charlie', 'Charlie')], default='None', max_length=50),
        ),
    ]
