# Generated by Django 4.1.2 on 2022-11-09 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NoccSchedulerApp', '0006_tour_type_of_customers_alter_tour_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='type_of_customers',
            field=models.CharField(choices=[('Financial Services', 'Financial Services'), ('Media', 'Media'), ('High Tech', 'High Tech'), ('Retail + Commerce', 'Retail + Commerce'), ('Gaming/OTT', 'Gaming/OTT'), ('Healthcare/Life Science', 'Healthcare/Life Science'), ('Manufacturing', 'Manufacturing'), ('Other', 'Other')], max_length=200),
        ),
    ]
