# Generated by Django 4.1.2 on 2022-11-18 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NoccSchedulerApp', '0007_alter_tour_type_of_customers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
