# Generated by Django 4.1.2 on 2022-11-30 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NoccSchedulerApp', '0008_alter_tour_end_time_alter_tour_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='opportunity_ID',
            field=models.CharField(blank=True, default=0, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='status',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Rejected', 'Rejected'), ('Approved', 'Approved'), ('Canceled', 'Canceled')], default='Requested', max_length=20),
        ),
    ]
