# Generated by Django 4.1.2 on 2022-11-30 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NoccSchedulerApp', '0009_alter_tour_opportunity_id_alter_tour_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='cc_this_request_to',
            field=models.EmailField(max_length=254),
        ),
    ]
