# Generated by Django 4.1.2 on 2022-11-30 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NoccSchedulerApp', '0010_alter_tour_cc_this_request_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='avail_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='availability',
            name='time_slots',
            field=models.TextField(max_length=5000, null=True),
        ),
    ]
