# Generated by Django 4.1.2 on 2022-12-08 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NoccSchedulerApp', '0011_alter_availability_avail_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='nocc_person_assigned',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
