# Generated by Django 4.1.2 on 2022-12-08 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NoccSchedulerApp', '0012_alter_tour_nocc_person_assigned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='time_slots',
        ),
        migrations.AddField(
            model_name='availability',
            name='avail_time',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
