# Generated by Django 4.1.2 on 2022-12-21 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NoccSchedulerApp', '0013_remove_availability_time_slots_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='nocc_person_assigned',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='type_of_customers',
            field=models.CharField(choices=[('Financial Services', 'Financial Services'), ('Media', 'Media'), ('High Tech', 'High Tech'), ('Retail + Commerce', 'Retail + Commerce'), ('Gaming/OTT', 'Gaming/OTT'), ('Healthcare/Life Science', 'Healthcare/Life Science'), ('Manufacturing', 'Manufacturing'), ('Other', 'Other')], default='Other', max_length=200),
        ),
    ]
