# Generated by Django 4.1.2 on 2022-12-22 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NoccSchedulerApp', '0014_alter_tour_nocc_person_assigned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='feedback_name',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='internal_or_external_audience',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='key_take_aways',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='overall_feedback',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='satisfaction',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='5', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='sessions_daily_work',
            field=models.CharField(blank=True, choices=[('Not relevant', 'Not relevant'), ('Relevant', 'Relevant'), ('Very relevant', 'Very relevant'), ('Did not attend', 'Did not attend')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='sessions_scheduling_arrangement',
            field=models.CharField(blank=True, choices=[('Not relevant', 'Not relevant'), ('Relevant', 'Relevant'), ('Very relevant', 'Very relevant'), ('Did not attend', 'Did not attend')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='sessions_speaker',
            field=models.CharField(blank=True, choices=[('Not relevant', 'Not relevant'), ('Relevant', 'Relevant'), ('Very relevant', 'Very relevant'), ('Did not attend', 'Did not attend')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='sessions_walls_displays',
            field=models.CharField(blank=True, choices=[('Not relevant', 'Not relevant'), ('Relevant', 'Relevant'), ('Very relevant', 'Very relevant'), ('Did not attend', 'Did not attend')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='sessions_welcoming',
            field=models.CharField(blank=True, choices=[('Not relevant', 'Not relevant'), ('Relevant', 'Relevant'), ('Very relevant', 'Very relevant'), ('Did not attend', 'Did not attend')], max_length=20, null=True),
        ),
    ]
