# Generated by Django 4.1.2 on 2022-12-22 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NoccSchedulerApp', '0015_tour_feedback_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='key_take_aways',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
