# Generated by Django 4.1.2 on 2023-01-04 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NoccSchedulerApp', '0016_alter_tour_key_take_aways'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='feedback',
        ),
        migrations.AddField(
            model_name='tour',
            name='customers_website',
            field=models.CharField(blank=True, default=0, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='cc_this_request_to',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='satisfaction',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=5, null=True),
        ),
    ]
