# Generated by Django 4.1.2 on 2023-01-04 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NoccSchedulerApp', '0017_remove_tour_feedback_tour_customers_website_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='customers_website',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
