# Generated by Django 4.1.2 on 2023-01-10 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NoccSchedulerApp', '0019_alter_tour_type_of_customers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='division',
            field=models.CharField(choices=[('P & RE', 'P & RE'), ('Customer & Industry', 'Customer & Industry'), ('marketing', 'Marketing'), ('Global Events', 'Global Events'), ('Marketing Strategy', 'Marketing Strategy'), ('Legal', 'Legal'), ('CTO', 'CTO'), ('CEO', 'CEO'), ('Global Sales', 'Global Sales'), ('Customer Success', 'Customer Success'), ('Global Services', 'Global Services'), ('Products & Enablement', 'Products & Enablement'), ('Compute', 'Compute'), ('Edge Delivery', 'Edge Delivery'), ('Edge Business Operations', 'Edge Business Operations'), ('Edge Experience', 'Edge Experience'), ('Other', 'Other')], max_length=50),
        ),
    ]
