# Generated by Django 4.1.2 on 2023-01-25 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NoccSchedulerApp', '0022_alter_tour_type_of_customers'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoccRepresentatives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NoccSchedulerApp.location')),
            ],
        ),
    ]
