# Generated by Django 4.1.2 on 2023-01-25 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NoccSchedulerApp', '0023_noccrepresentatives'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noccrepresentatives',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
