# Generated by Django 4.1.2 on 2023-01-30 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NoccSchedulerApp', '0024_alter_noccrepresentatives_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='nocc_representatives_list',
        ),
        migrations.AddField(
            model_name='tour',
            name='feedback_status',
            field=models.CharField(choices=[('Request not sent', 'Request not sent'), ('Requested', 'Requested'), ('No answer 3 days', 'No answer 3 days'), ('Provided', 'Provided')], default='Request not sent', max_length=30),
        ),
    ]
