# Generated by Django 4.1.2 on 2023-01-31 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NoccSchedulerApp', '0025_remove_location_nocc_representatives_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='feedback_status',
            field=models.CharField(choices=[('Request not sent', 'Request not sent'), ('Request sent', 'Request sent'), ('No answer 3 days', 'No answer 3 days'), ('Provided', 'Provided')], default='Request not sent', max_length=30),
        ),
    ]
